In [1]:
import numpy as np

In [4]:
"""
1.3.1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами. 
"""
chessboard = np.zeros((8, 8), dtype=int)

chessboard[1::2, ::2] = 1  # Нечетные строки, четные столбцы
chessboard[::2, 1::2] = 1  # Четные строки, нечетные столбцы

print("Шахматная доска 8x8:")
print(chessboard)

Шахматная доска 8x8:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
"""
1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию
"""

import numpy as np

row_values = np.arange(5)

matrix = np.zeros((5, 5))
matrix += row_values

print("Матрица 5x5 со значениями в строках от 0 до 4:")
print(matrix)

Матрица 5x5 со значениями в строках от 0 до 4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [6]:
"""
1.3.3 Задание: Создать массив 3x3x3 со случайными значениями.
"""

import numpy as np

random_3d_array = np.random.random((3, 3, 3))

print("Массив 3x3x3 со случайными значениями:")
print(random_3d_array)

Массив 3x3x3 со случайными значениями:
[[[0.9126045  0.09520882 0.66666314]
  [0.17032375 0.74402077 0.17076337]
  [0.16434825 0.92376774 0.23314473]]

 [[0.21376119 0.98227335 0.56977527]
  [0.25437161 0.19247585 0.87890861]
  [0.2287113  0.01563041 0.56853439]]

 [[0.35218797 0.99882866 0.10632427]
  [0.24956529 0.66747493 0.46976455]
  [0.70219442 0.24005484 0.48804553]]]


In [7]:
"""
1.3.4 Задание: Создать матрицу с 0 внутри, и 1 на границах.
"""

import numpy as np

inner = np.zeros((3, 3))

matrix_with_border = np.pad(inner, pad_width=1, mode='constant', constant_values=1)

print("Матрица 5x5 с 0 внутри и 1 на границах:")
print(matrix_with_border)

Матрица 5x5 с 0 внутри и 1 на границах:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
"""
1.3.5 Задание: Создайте массив и отсортируйте его по убыванию.
"""

import numpy as np

arr = np.array([5, 2, 8, 1, 9, 3])

sorted_desc = np.sort(arr)[::-1]

print("Исходный массив:", arr)
print("Отсортированный массив по убыванию:", sorted_desc)

In [ ]:
"""
1.3.6 Задание: Создайте матрицу, выведите ее форму, размер и размерность.
"""
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

print("Матрица:")
print(matrix)
print("Форма (shape):", matrix.shape)
print("Размер (size - общее количество элементов):", matrix.size)
print("Размерность (ndim - количество осей):", matrix.ndim)

In [8]:
"""
2.3.2 Задание: Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных.
"""
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"

df = pd.read_csv(url)

print("Первые 5 строк DataFrame:")
print(df.head())

Первые 5 строк DataFrame:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa


In [9]:
"""
2.3.3 Задание: Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.
"""

import pandas as pd

# Загрузка данных (из предыдущего задания 2.3.2)
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

# 2.2.5 Анализ характеристик
print("=== Первые 5 строк (head) ===")
print(df.head())
print("\n=== Последние 3 строки (tail) ===")
print(df.tail(3))
print("\n=== Форма DataFrame (shape) ===")
print(df.shape)
print("\n=== Описательная статистика (describe) ===")
print(df.describe())

# 2.2.6 Выборка данных
print("\n=== 2.2.6: Выборка данных ===")
# Выбрать первую строку с помощью iloc
first_row = df.iloc[0]
print("Первая строка (iloc[0]):")
print(first_row)
# Выбрать столбец 'species' с помощью loc
species_column = df.loc[:, 'species']
print("\nСтолбец 'species' (loc[:, 'species']):")
print(species_column.head()) # Показываем только первые 5 для краткости

# 2.2.7 Отбор строк по условию
print("\n=== 2.2.7: Отбор строк по условию ===")
# Создаем новый DataFrame из цветков вида 'versicolor'
df_versicolor = df[df['species'] == 'versicolor']
print("DataFrame с цветками 'versicolor' (первые 5 строк):")
print(df_versicolor.head())

=== Первые 5 строк (head) ===
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

=== Последние 3 строки (tail) ===
     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
147  virginica  
148  virginica  
149  virginica  

=== Форма DataFrame (shape) ===
(150, 5)

=== Описательная статистика (describe) ===
       sepal_length_cm  sepal_wi

In [ ]:
"""
3.3.2 Задание: Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго
(sepal_width_cm) с задействованием z-масштабирования.
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

df_normalized = df.copy()

min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

df_normalized['sepal_length_cm'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])

df_normalized['sepal_width_cm'] = standard_scaler.fit_transform(df[['sepal_width_cm']])

print("Оригинальные первые 5 строк:")
print(df.head())
print("\nНормализованные первые 5 строк:")
print(df_normalized.head())

print("\nСтатистика для нормализованного 'sepal_length_cm' (должны быть min=0, max=1):")
print(df_normalized['sepal_length_cm'].describe())
print("\nСтатистика для нормализованного 'sepal_width_cm' (должны быть mean~0, std=1):")
print(df_normalized['sepal_width_cm'].describe())

Оригинальные первые 5 строк:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

Нормализованные первые 5 строк:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa

Статистика для нормализов