In [10]:
# 1.2
import sympy as sp

augmented_matrix = sp.Matrix([
    [5, -1, 5,  9, -2, -3],
    [3,  0, 6,  9, -1,  4],
    [2,  0, 4,  6, -1,  0]
])

print("Исходная расширенная матрица:")
sp.pprint(augmented_matrix)

rref_matrix, pivot_columns = augmented_matrix.rref()

print("а) rref(A|b) =")
sp.pprint(rref_matrix)

# Разделение расширенной матрицы на матрицу коэффициентов A и вектор свободных членов b
A = augmented_matrix[:, :-1]
b = augmented_matrix[:, -1]

x1, x2, x3, x4, x5 = sp.symbols('x1 x2 x3 x4 x5')

solution = sp.linsolve((A, b), (x1, x2, x3, x4, x5))

print("б) Общее решение системы:")
sp.pprint(tuple(solution)[0]) # type: ignore

Исходная расширенная матрица:
⎡5  -1  5  9  -2  -3⎤
⎢                   ⎥
⎢3  0   6  9  -1  4 ⎥
⎢                   ⎥
⎣2  0   4  6  -1  0 ⎦
а) rref(A|b) =
⎡1  0  2  3  0  4⎤
⎢                ⎥
⎢0  1  5  6  0  7⎥
⎢                ⎥
⎣0  0  0  0  1  8⎦
б) Общее решение системы:
(-2⋅x₃ - 3⋅x₄ + 4, -5⋅x₃ - 6⋅x₄ + 7, x₃, x₄, 8)


In [17]:
# 1.3
import sympy as sp

x, y, z, u = sp.symbols('x y z u')

eq1 = sp.Eq(32*x + 97*y + 90*z + 48*u, 47)
eq2 = sp.Eq(35*x + 84*y + 91*z + 54*u, 40)
eq3 = sp.Eq(17*x + 18*y + 21*z + 13*u, 37)

solution = sp.linsolve([eq1, eq2, eq3], (x, y, z, u))

sol_tuple = list(solution)[0] # type: ignore
y_expr = sol_tuple[1]

print("Зависимость y от x:")
sp.pprint(y_expr)

poly_y = sp.Poly(y_expr, x)
coeffs = poly_y.all_coeffs()
print(coeffs)

b_val = coeffs[0]
a_val = coeffs[1]

print(f"1) a = {a_val}")
print(f"2) b = {b_val}")

Зависимость y от x:
2131⋅u   6325
────── + ────
 5488    5488
[2131*u/5488 + 6325/5488]


IndexError: list index out of range

In [ ]:
# 1.4
import numpy as np

A = np.array([[3, 0, 2], [0, 1, 3], [2, 2, 0], [0, 1, 0]])
B = np.array([
  [1,2,-1,2],
  [-2,-1,1,2],
  [2,1,1,2]
])
C = np.array([
  [0,-4,6,1],
  [2,2,-5,-2],
  [2,-2,6,4],
  [1,3,0,1]
])
print(np.linalg.matmul(A,B) + C)

[[ 7  4  5 11]
 [ 6  4 -1  6]
 [ 0  0  6 12]
 [-1  2  1  3]]


In [16]:
# 1.5
import numpy as np

A = []
for i in range(1,5):
  A.append([])
  for j in range(1,5):
    A[-1].append(min(i,j))
print("1)\t", np.linalg.det(A))

B = []
for i in range(1,5):
  B.append([])
  for j in range(1,5):
    B[-1].append(max(i,j))
print("2)\t",np.linalg.det(B))

C = []
for i in range(1,5):
  C.append([])
  for j in range(1,5):
    C[-1].append(abs(i-j))
print("3)\t",np.linalg.det(C))

1)	 1.0
2)	 -4.0
3)	 -12.0


In [ ]:
# 1.6
import numpy as np
from itertools import product

def max_det_order_6():
    n = 6
    max_determinant = 0
    best_matrix = None
    
    first_row = np.ones(n, dtype=np.int8)
    all_rows = list(product([-1, 0, 1], repeat=n))
    valid_rows = [np.array(r, dtype=np.int8) for r in all_rows if any(v != 0 for v in r)]
    
    checked = 0
    
    def search(current_matrix, depth):
        nonlocal max_determinant, best_matrix, checked
        
        if depth == n:
            det = abs(round(np.linalg.det(current_matrix)))
            if det > max_determinant:
                max_determinant = det
                best_matrix = current_matrix.copy()
            return
        
        for row in valid_rows:
            current_matrix[depth] = row
            
            if depth >= 1:
                rank = np.linalg.matrix_rank(current_matrix[:depth+1])
                if rank < depth + 1:
                    continue
            
            search(current_matrix, depth + 1)
    
    matrix = np.zeros((n, n), dtype=np.int8)
    matrix[0] = first_row
    
    print("Запуск поиска...")
    search(matrix, 1)
    
    return max_determinant, best_matrix

max_det, optimal_matrix = max_det_order_6()
print(f"Максимальный определитель: {max_det}")
print("Пример оптимальной матрицы:")
print(optimal_matrix)

Запуск поиска...
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6
вышли 6

KeyboardInterrupt: 

In [6]:
# 1.9
import numpy as np

I = np.array([[1,0],[0,1]])
gamma = 0.057
A = np.array([[7,14],[9,1]]) * gamma

def Smn(m:int,n:int):
  sum = np.zeros([2,2])
  for i in range(m,n+1):
    sum += A**i
  return sum

def Bm(m:int):
  return np.linalg.matmul(np.linalg.inv(I-A),A**m)

S = Smn(4,70)
print(np.max(S))

B = Bm(4)
print(np.max(B))

2.0075209119306363
2.4300412155067783
